name: "Picsew"
alias: "A Developer's Faux Pas"
author: "Ezra"
description: "Illustration artist. Trilingual. Conlanger.<br/>Former <!--CTO, -->PM, DPO & CO-FD of Jayne startup.<br/>27 y/o full-stack software developer on PC, Linux, Android, iOS and OS X platforms.<br/>Crafty. Blogger. Traveller.<br/>Big fan of Apple. Love of colour.<br/>Doggies are my fave."
url: "https://picsew.cn"